config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships

  resources :beer_clubs

  resources :users
  resources :sessions, only: [:new, :create]

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :beers

  resources :breweries

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ratebeer</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
<div class"navibar">
<%= link_to 'breweries', breweries_path %>
<%= link_to 'beers', beers_path %>
<%= link_to 'beer clubs', beer_clubs_path %>
<%= link_to 'ratings', ratings_path %>
<%= link_to 'users', users_path %>
<span>| </span>
<% if not current_user.nil? %>
<%= link_to current_user.username, user_path(current_user.id) %>
<%= link_to 'rate a beer', new_rating_path %>
<%= link_to 'join a club', new_membership_path %>
<%= link_to 'sign out', signout_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
<%= link_to 'sign in', signin_path %>
<%= link_to 'sign up', signup_path %>

<% end %>
</div>

<% if session[:last_rating].nil? %>
<p>No ratings given</p>
<% else %>
<p>Previous rating: <%= session[:last_rating] %></p>
<% end %>

<%= yield %>

</body>
</html>